# Generated by Django 5.2.5 on 2025-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('published', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/profile')),
            ],
        ),
    ]
